name: Publish crates.io
on:
  push:
    tags: [v*]

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: git clone --depth 1 https://github.com/celestia-island/yuuka.git ../yuuka
      - uses: Swatinem/rust-cache@v2
      - run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
      - run: cargo publish -p kirino --allow-dirty 2>&1; true
